PREFIX=$(HOME)/torch/install
CFLAGS=-I$(PREFIX)/include/THC -I$(PREFIX)/include/TH -I$(PREFIX)/include
LDFLAGS_NVCC=-L$(PREFIX)/lib -Xlinker -rpath,$(PREFIX)/lib -lluaT -lTHC -lTH -lpng
LDFLAGS_CPP=-L$(PREFIX)/lib -lluaT -lTH `pkg-config --libs opencv`

all: libutil.so libcv.so

libutil.so: util.cu
	nvcc -arch sm_35 -O3 --compiler-options '-fPIC' -o libutil.so --shared util.cu $(CFLAGS) $(LDFLAGS_NVCC)

libcv.so: cv.cpp
	g++ -O3 -fPIC -o libcv.so -shared cv.cpp $(CFLAGS) $(LDFLAGS_CPP)

clean:
	rm -f libutil.so libcv.so
